# Generated by Django 3.2.6 on 2021-08-30 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("username", models.CharField(max_length=100, unique=True)),
                ("email", models.CharField(max_length=200)),
                ("full_name", models.CharField(max_length=200)),
                ("zipcode", models.IntegerField()),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("collection_name", models.CharField(max_length=100)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection",
<<<<<<< HEAD
                        to="users.appuser",
=======
                        to=settings.AUTH_USER_MODEL,
>>>>>>> workinglogin
                    ),
                ),
                (
                    "restaurants",
                    models.ManyToManyField(blank=True, to="restaurants.Restaurant"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="appuser",
            name="collections",
            field=models.ManyToManyField(blank=True, to="users.Collection"),
        ),
    ]
