# Generated by Django 3.2.6 on 2021-08-30 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auto_20210830_0546"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="appuser",
            managers=[],
        ),
    ]
